spring:
  profiles:
    active: local

# JWT
jwt:
  expiration: 259200000  # 3일 (단위: 밀리초)

redis:
  ttl:
    product-list: 5
    product-detail: 7
    order-idempotency: 10

kafka:
  topic:
    order: order-create